/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BlogActivityPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  feeds: [],
  activityData: {},
  lastFetched: null,
  defaultView: "yearly",
  colorTheme: "auto"
};
var VIEW_TYPE_BLOG_ACTIVITY = "blog-activity-view";
var RSSParser = class {
  static async fetchFeed(url) {
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "GET",
        headers: {
          "Accept": "application/rss+xml, application/xml, text/xml, application/atom+xml"
        }
      });
      const parser = new DOMParser();
      const doc = parser.parseFromString(response.text, "text/xml");
      const rssItems = doc.querySelectorAll("item");
      if (rssItems.length > 0) {
        return this.parseRSSItems(rssItems);
      }
      const atomEntries = doc.querySelectorAll("entry");
      if (atomEntries.length > 0) {
        return this.parseAtomEntries(atomEntries);
      }
      return [];
    } catch (error) {
      console.error("Error fetching RSS feed:", error);
      throw error;
    }
  }
  static parseRSSItems(items) {
    const posts = [];
    items.forEach((item) => {
      var _a, _b, _c, _d;
      const title = ((_a = item.querySelector("title")) == null ? void 0 : _a.textContent) || "Untitled";
      const link = ((_b = item.querySelector("link")) == null ? void 0 : _b.textContent) || "";
      const pubDate = ((_c = item.querySelector("pubDate")) == null ? void 0 : _c.textContent) || ((_d = item.querySelector("dc\\:date")) == null ? void 0 : _d.textContent) || "";
      if (pubDate) {
        posts.push({
          title,
          url: link,
          publishedDate: (0, import_obsidian.moment)(pubDate).format("YYYY-MM-DD"),
          feedId: "",
          feedName: "",
          platform: ""
        });
      }
    });
    return posts;
  }
  static parseAtomEntries(entries) {
    const posts = [];
    entries.forEach((entry) => {
      var _a, _b, _c;
      const title = ((_a = entry.querySelector("title")) == null ? void 0 : _a.textContent) || "Untitled";
      const linkEl = entry.querySelector('link[rel="alternate"]') || entry.querySelector("link");
      const link = (linkEl == null ? void 0 : linkEl.getAttribute("href")) || "";
      const published = ((_b = entry.querySelector("published")) == null ? void 0 : _b.textContent) || ((_c = entry.querySelector("updated")) == null ? void 0 : _c.textContent) || "";
      if (published) {
        posts.push({
          title,
          url: link,
          publishedDate: (0, import_obsidian.moment)(published).format("YYYY-MM-DD"),
          feedId: "",
          feedName: "",
          platform: ""
        });
      }
    });
    return posts;
  }
};
var BlogActivityView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.currentView = plugin.settings.defaultView;
  }
  getViewType() {
    return VIEW_TYPE_BLOG_ACTIVITY;
  }
  getDisplayText() {
    return "Blog Activity";
  }
  getIcon() {
    return "calendar-with-checkmark";
  }
  async onOpen() {
    await this.render();
  }
  async onClose() {
  }
  async render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("blog-activity-container");
    container.removeClass(
      "blog-activity-theme-auto",
      "blog-activity-theme-light",
      "blog-activity-theme-dark"
    );
    container.addClass(`blog-activity-theme-${this.plugin.settings.colorTheme}`);
    const header = container.createDiv({ cls: "blog-activity-header" });
    header.createEl("h2", { text: "Blog Activity" });
    const headerActions = header.createDiv({ cls: "blog-activity-header-actions" });
    const themeBtn = headerActions.createEl("button", {
      cls: "blog-activity-theme-btn"
    });
    this.updateThemeButton(themeBtn);
    themeBtn.addEventListener("click", async () => {
      const order = ["auto", "light", "dark"];
      const next = order[(order.indexOf(this.plugin.settings.colorTheme) + 1) % order.length];
      this.plugin.settings.colorTheme = next;
      await this.plugin.saveSettings();
      await this.render();
    });
    const refreshBtn = headerActions.createEl("button", {
      cls: "blog-activity-refresh-btn",
      text: "Refresh"
    });
    refreshBtn.addEventListener("click", async () => {
      await this.plugin.fetchAllFeeds();
      await this.render();
    });
    const toggleContainer = container.createDiv({ cls: "blog-activity-toggle" });
    const views = ["weekly", "monthly", "yearly"];
    views.forEach((view) => {
      const btn = toggleContainer.createEl("button", {
        cls: `toggle-btn ${this.currentView === view ? "active" : ""}`,
        text: view.charAt(0).toUpperCase() + view.slice(1)
      });
      btn.addEventListener("click", () => {
        this.currentView = view;
        this.render();
      });
    });
    const stats = this.calculateStats();
    const statsContainer = container.createDiv({ cls: "blog-activity-stats" });
    statsContainer.createDiv({ cls: "stat" }).innerHTML = `<span class="stat-value">${stats.totalPosts}</span><span class="stat-label">Total Posts</span>`;
    statsContainer.createDiv({ cls: "stat" }).innerHTML = `<span class="stat-value">${stats.postsInPeriod}</span><span class="stat-label">In Period</span>`;
    statsContainer.createDiv({ cls: "stat" }).innerHTML = `<span class="stat-value">${stats.currentStreak}</span><span class="stat-label">Current Streak</span>`;
    statsContainer.createDiv({ cls: "stat" }).innerHTML = `<span class="stat-value">${stats.longestStreak}</span><span class="stat-label">Longest Streak</span>`;
    const heatmapContainer = container.createDiv({ cls: "blog-activity-heatmap-container" });
    this.renderHeatmap(heatmapContainer);
    const legendContainer = container.createDiv({ cls: "blog-activity-legend" });
    legendContainer.createSpan({ text: "Less" });
    for (let i = 0; i <= 4; i++) {
      legendContainer.createDiv({ cls: `legend-cell level-${i}` });
    }
    legendContainer.createSpan({ text: "More" });
    const recentContainer = container.createDiv({ cls: "blog-activity-recent" });
    recentContainer.createEl("h3", { text: "Recent Posts" });
    this.renderRecentPosts(recentContainer);
  }
  updateThemeButton(btn) {
    const labels = {
      auto: "\u25D1 Auto",
      light: "\u2600 Light",
      dark: "\u263E Dark"
    };
    const theme = this.plugin.settings.colorTheme;
    btn.textContent = labels[theme];
    btn.setAttribute("aria-label", `Color theme: ${theme}. Click to change.`);
    btn.setAttribute("title", `Color theme: ${theme}. Click to change.`);
  }
  renderHeatmap(container) {
    const heatmap = container.createDiv({ cls: "heatmap" });
    const { startDate, endDate, weeks } = this.getDateRange();
    const activityMap = this.getActivityMap(startDate, endDate);
    const monthLabels = heatmap.createDiv({ cls: "month-labels" });
    monthLabels.createDiv({ cls: "day-label-spacer" });
    const months = this.getMonthLabels(startDate, endDate);
    months.forEach((month) => {
      const label = monthLabels.createDiv({ cls: "month-label" });
      label.textContent = month.name;
      label.style.gridColumn = `span ${month.weeks}`;
    });
    const dayLabels = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
    const dayLabelContainer = heatmap.createDiv({ cls: "day-labels" });
    dayLabels.forEach((day, index) => {
      if (index % 2 === 1) {
        dayLabelContainer.createDiv({ cls: "day-label", text: day });
      } else {
        dayLabelContainer.createDiv({ cls: "day-label" });
      }
    });
    const grid = heatmap.createDiv({ cls: "heatmap-grid" });
    grid.style.gridTemplateColumns = `repeat(${weeks}, var(--cell-size))`;
    const current = (0, import_obsidian.moment)(startDate).startOf("week");
    const end = (0, import_obsidian.moment)(endDate).endOf("week");
    while (current.isSameOrBefore(end)) {
      const dateStr = current.format("YYYY-MM-DD");
      const posts = activityMap[dateStr] || [];
      const level = this.getActivityLevel(posts.length);
      const cell = grid.createDiv({
        cls: `heatmap-cell level-${level}`
      });
      if (current.isBefore(startDate) || current.isAfter(endDate)) {
        cell.addClass("outside-range");
      }
      cell.setAttribute("data-date", dateStr);
      cell.setAttribute("data-count", posts.length.toString());
      const tooltipText = posts.length === 0 ? `No posts on ${current.format("MMM D, YYYY")}` : `${posts.length} post${posts.length > 1 ? "s" : ""} on ${current.format("MMM D, YYYY")}`;
      cell.setAttribute("aria-label", tooltipText);
      cell.setAttribute("title", tooltipText);
      if (posts.length > 0) {
        cell.addEventListener("click", () => {
          this.showDayPosts(dateStr, posts);
        });
        cell.addClass("clickable");
      }
      current.add(1, "day");
    }
    requestAnimationFrame(() => {
      container.scrollLeft = container.scrollWidth;
    });
  }
  getDateRange() {
    const endDate = (0, import_obsidian.moment)().endOf("day");
    let startDate;
    let weeks;
    switch (this.currentView) {
      case "weekly":
        startDate = (0, import_obsidian.moment)().subtract(7, "weeks").startOf("week");
        weeks = 8;
        break;
      case "monthly":
        startDate = (0, import_obsidian.moment)().subtract(6, "months").startOf("week");
        weeks = Math.ceil((0, import_obsidian.moment)().diff(startDate, "weeks")) + 1;
        break;
      case "yearly":
      default:
        startDate = (0, import_obsidian.moment)().subtract(1, "year").startOf("week");
        weeks = 53;
        break;
    }
    return { startDate, endDate, weeks };
  }
  getActivityMap(startDate, endDate) {
    const activityMap = {};
    const activityData = this.plugin.settings.activityData;
    Object.entries(activityData).forEach(([date, posts]) => {
      const dateMoment = (0, import_obsidian.moment)(date);
      if (dateMoment.isBetween(startDate, endDate, "day", "[]")) {
        activityMap[date] = posts;
      }
    });
    return activityMap;
  }
  getActivityLevel(count) {
    if (count === 0)
      return 0;
    if (count === 1)
      return 1;
    if (count === 2)
      return 2;
    if (count <= 4)
      return 3;
    return 4;
  }
  getMonthLabels(startDate, endDate) {
    const months = [];
    const current = (0, import_obsidian.moment)(startDate).startOf("month");
    while (current.isSameOrBefore(endDate)) {
      const monthStart = import_obsidian.moment.max(current.clone().startOf("month"), startDate);
      const monthEnd = import_obsidian.moment.min(current.clone().endOf("month"), endDate);
      const weeksInMonth = Math.ceil(monthEnd.diff(monthStart, "days") / 7);
      if (weeksInMonth > 0) {
        months.push({
          name: current.format("MMM"),
          weeks: Math.max(1, weeksInMonth)
        });
      }
      current.add(1, "month");
    }
    return months;
  }
  calculateStats() {
    const activityData = this.plugin.settings.activityData;
    const { startDate, endDate } = this.getDateRange();
    let totalPosts = 0;
    let postsInPeriod = 0;
    Object.entries(activityData).forEach(([date, posts]) => {
      totalPosts += posts.length;
      if ((0, import_obsidian.moment)(date).isBetween(startDate, endDate, "day", "[]")) {
        postsInPeriod += posts.length;
      }
    });
    const { currentStreak, longestStreak } = this.calculateStreaks();
    return { totalPosts, postsInPeriod, currentStreak, longestStreak };
  }
  calculateStreaks() {
    const activityData = this.plugin.settings.activityData;
    const sortedDates = Object.keys(activityData).filter((date) => activityData[date].length > 0).sort();
    if (sortedDates.length === 0) {
      return { currentStreak: 0, longestStreak: 0 };
    }
    const weekMap = {};
    sortedDates.forEach((date) => {
      const weekKey = (0, import_obsidian.moment)(date).startOf("week").format("YYYY-WW");
      weekMap[weekKey] = true;
    });
    const weeks = Object.keys(weekMap).sort();
    let longestStreak = 1;
    let currentStreak = 0;
    let tempStreak = 1;
    const currentWeek = (0, import_obsidian.moment)().startOf("week").format("YYYY-WW");
    const lastWeek = (0, import_obsidian.moment)().subtract(1, "week").startOf("week").format("YYYY-WW");
    for (let i = 1; i < weeks.length; i++) {
      const prevWeek = (0, import_obsidian.moment)(weeks[i - 1], "YYYY-WW");
      const currWeek = (0, import_obsidian.moment)(weeks[i], "YYYY-WW");
      if (currWeek.diff(prevWeek, "weeks") === 1) {
        tempStreak++;
        longestStreak = Math.max(longestStreak, tempStreak);
      } else {
        tempStreak = 1;
      }
    }
    if (weeks.includes(currentWeek) || weeks.includes(lastWeek)) {
      currentStreak = tempStreak;
    }
    return { currentStreak, longestStreak };
  }
  showDayPosts(date, posts) {
    const formattedDate = (0, import_obsidian.moment)(date).format("MMMM D, YYYY");
    new import_obsidian.Notice(`Posts on ${formattedDate}:
${posts.map((p) => `- ${p.title}`).join("\n")}`);
  }
  renderRecentPosts(container) {
    const activityData = this.plugin.settings.activityData;
    const allPosts = [];
    Object.values(activityData).forEach((posts) => {
      allPosts.push(...posts);
    });
    allPosts.sort((a, b) => (0, import_obsidian.moment)(b.publishedDate).diff((0, import_obsidian.moment)(a.publishedDate)));
    const recentPosts = allPosts.slice(0, 10);
    if (recentPosts.length === 0) {
      container.createEl("p", {
        text: "No posts yet. Add your blog RSS feeds in settings and click Refresh.",
        cls: "no-posts-message"
      });
      return;
    }
    const list = container.createEl("ul", { cls: "recent-posts-list" });
    recentPosts.forEach((post) => {
      const item = list.createEl("li", { cls: "recent-post-item" });
      const link = item.createEl("a", {
        href: post.url,
        text: post.title,
        cls: "post-title"
      });
      link.setAttr("target", "_blank");
      const meta = item.createDiv({ cls: "post-meta" });
      meta.createSpan({ text: post.feedName, cls: "post-feed" });
      meta.createSpan({ text: " \u2022 " });
      meta.createSpan({
        text: (0, import_obsidian.moment)(post.publishedDate).format("MMM D, YYYY"),
        cls: "post-date"
      });
    });
  }
};
var BlogActivitySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Blog Activity Tracker Settings" });
    new import_obsidian.Setting(containerEl).setName("Default view").setDesc("Choose the default time range for the activity view").addDropdown(
      (dropdown) => dropdown.addOption("weekly", "Weekly (8 weeks)").addOption("monthly", "Monthly (6 months)").addOption("yearly", "Yearly (52 weeks)").setValue(this.plugin.settings.defaultView).onChange(async (value) => {
        this.plugin.settings.defaultView = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Color theme").setDesc(
      "Choose how the activity view is colored. Auto follows your Obsidian theme; Light and Dark force that appearance regardless of your theme."
    ).addDropdown(
      (dropdown) => dropdown.addOption("auto", "Auto (match Obsidian)").addOption("light", "Light").addOption("dark", "Dark").setValue(this.plugin.settings.colorTheme).onChange(async (value) => {
        this.plugin.settings.colorTheme = value;
        await this.plugin.saveSettings();
        this.plugin.refreshOpenViews();
      })
    );
    containerEl.createEl("h3", { text: "RSS Feeds" });
    containerEl.createEl("p", {
      text: "Add your blog RSS feeds below. Common feed URLs:",
      cls: "setting-item-description"
    });
    const feedHelp = containerEl.createEl("ul", { cls: "feed-help" });
    feedHelp.createEl("li", { text: "Substack: https://yourname.substack.com/feed" });
    feedHelp.createEl("li", { text: "Medium: https://medium.com/feed/@yourname" });
    feedHelp.createEl("li", { text: "Ghost: https://yourblog.com/rss/" });
    new import_obsidian.Setting(containerEl).setName("Add new feed").setDesc("Add a new RSS feed to track").addButton(
      (button) => button.setButtonText("Add Feed").onClick(() => {
        this.plugin.settings.feeds.push({
          id: Date.now().toString(),
          name: "New Blog",
          url: "",
          platform: "other",
          enabled: true
        });
        this.plugin.saveSettings();
        this.display();
      })
    );
    this.plugin.settings.feeds.forEach((feed, index) => {
      const feedContainer = containerEl.createDiv({ cls: "feed-setting-container" });
      new import_obsidian.Setting(feedContainer).setName(`Feed ${index + 1}: ${feed.name}`).setDesc(feed.url || "No URL set").addToggle(
        (toggle) => toggle.setValue(feed.enabled).onChange(async (value) => {
          feed.enabled = value;
          await this.plugin.saveSettings();
        })
      ).addButton(
        (button) => button.setButtonText("Edit").onClick(() => {
          this.showFeedEditor(feed, index);
        })
      ).addButton(
        (button) => button.setButtonText("Delete").setWarning().onClick(async () => {
          this.plugin.settings.feeds.splice(index, 1);
          await this.plugin.saveSettings();
          this.display();
        })
      );
    });
    containerEl.createEl("h3", { text: "Data Management" });
    new import_obsidian.Setting(containerEl).setName("Fetch all feeds").setDesc("Manually fetch all enabled RSS feeds").addButton(
      (button) => button.setButtonText("Fetch Now").onClick(async () => {
        await this.plugin.fetchAllFeeds();
        new import_obsidian.Notice("Feeds fetched successfully!");
      })
    );
    new import_obsidian.Setting(containerEl).setName("Clear activity data").setDesc("Remove all stored activity data").addButton(
      (button) => button.setButtonText("Clear Data").setWarning().onClick(async () => {
        this.plugin.settings.activityData = {};
        this.plugin.settings.lastFetched = null;
        await this.plugin.saveSettings();
        new import_obsidian.Notice("Activity data cleared!");
      })
    );
    if (this.plugin.settings.lastFetched) {
      containerEl.createEl("p", {
        text: `Last fetched: ${(0, import_obsidian.moment)(this.plugin.settings.lastFetched).format("MMMM D, YYYY h:mm A")}`,
        cls: "setting-item-description"
      });
    }
  }
  showFeedEditor(feed, index) {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Edit Feed" });
    new import_obsidian.Setting(containerEl).setName("Feed name").setDesc("A friendly name for this feed").addText(
      (text) => text.setValue(feed.name).onChange(async (value) => {
        feed.name = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Feed URL").setDesc("The RSS feed URL").addText(
      (text) => text.setPlaceholder("https://example.com/feed").setValue(feed.url).onChange(async (value) => {
        feed.url = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Platform").setDesc("The blog platform (for display purposes)").addDropdown(
      (dropdown) => dropdown.addOption("substack", "Substack").addOption("medium", "Medium").addOption("ghost", "Ghost").addOption("other", "Other").setValue(feed.platform).onChange(async (value) => {
        feed.platform = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Test feed").setDesc("Test if the feed URL is valid and working").addButton(
      (button) => button.setButtonText("Test").onClick(async () => {
        try {
          const posts = await RSSParser.fetchFeed(feed.url);
          new import_obsidian.Notice(`Success! Found ${posts.length} posts.`);
        } catch (error) {
          new import_obsidian.Notice(`Error: Could not fetch feed. Check the URL.`);
        }
      })
    );
    new import_obsidian.Setting(containerEl).addButton(
      (button) => button.setButtonText("Back to Settings").onClick(() => {
        this.display();
      })
    );
  }
};
var BlogActivityPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_BLOG_ACTIVITY, (leaf) => new BlogActivityView(leaf, this));
    this.addRibbonIcon("calendar-with-checkmark", "Blog Activity", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-blog-activity",
      name: "Open Blog Activity View",
      callback: () => {
        this.activateView();
      }
    });
    this.addCommand({
      id: "refresh-blog-feeds",
      name: "Refresh Blog Feeds",
      callback: async () => {
        await this.fetchAllFeeds();
        new import_obsidian.Notice("Blog feeds refreshed!");
      }
    });
    this.addSettingTab(new BlogActivitySettingTab(this.app, this));
    if (!this.settings.lastFetched || (0, import_obsidian.moment)().diff((0, import_obsidian.moment)(this.settings.lastFetched), "hours") >= 1) {
      setTimeout(() => {
        this.fetchAllFeeds();
      }, 5e3);
    }
  }
  async onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_BLOG_ACTIVITY);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: VIEW_TYPE_BLOG_ACTIVITY, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async fetchAllFeeds() {
    const enabledFeeds = this.settings.feeds.filter((f) => f.enabled && f.url);
    if (enabledFeeds.length === 0) {
      return;
    }
    for (const feed of enabledFeeds) {
      try {
        const posts = await RSSParser.fetchFeed(feed.url);
        posts.forEach((post) => {
          post.feedId = feed.id;
          post.feedName = feed.name;
          post.platform = feed.platform;
          const date = post.publishedDate;
          if (!this.settings.activityData[date]) {
            this.settings.activityData[date] = [];
          }
          const exists = this.settings.activityData[date].some(
            (p) => p.url === post.url || p.title === post.title && p.feedId === post.feedId
          );
          if (!exists) {
            this.settings.activityData[date].push(post);
          }
        });
      } catch (error) {
        console.error(`Error fetching feed ${feed.name}:`, error);
        new import_obsidian.Notice(`Failed to fetch ${feed.name}`);
      }
    }
    this.settings.lastFetched = (0, import_obsidian.moment)().toISOString();
    await this.saveSettings();
    await this.refreshOpenViews();
  }
  async refreshOpenViews() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_BLOG_ACTIVITY);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view && view.render) {
        await view.render();
      }
    }
  }
};
